services:
    acribot:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        volumes:
            - .:/usr/src/app
        command: npm start
        restart: always
